### ISSUE TITLE
Error while compiling with Electron

### ISSUE THREAD

**Issue by Avocadocs** [theace0296/steamworks-node#2]
Hello,
I'm very interessted for your lib but I can't make it working :(
I did all following small guide but I'm getting
`(node:5804) UnhandledPromiseRejectionWarning: Error: The module '\\?\C:\Users\--\electron\node_modules\@theace0296\steamworks\bin\steamworks.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 106. Please try re-compiling or re-installing`
And recompiling/redownloading doesn't fix anything.

OS: Windows 10
Node.js version: v16.15.1
npm version: 8.11.0

Thanks!

**Comment by theace0296** [comment]
I'm not super familiar with Electron, but I believe you have to compile the module using Electron's binaries. Last time I used electron you could use `electron-rebuild` to do that.

**Comment by GrandMod** [comment]
Same issue. I tried to rebuild package for electron v17.4.7, but during compilation I got an error
Command: `npx node-gyp rebuild --directory=lib --target=17.4.7 --arch=x64 --dist-url=https://electronjs.org/headers`

Log:
```gyp
gyp info it worked if it ends with ok
gyp info using node-gyp@8.4.1
gyp info using node@17.6.0 | win32 | x64
gyp info chdir lib
gyp info find Python using Python version 3.10.4 found at "path\to\AppData\Local\Programs\Python\Python310\python.exe"
gyp info find VS using VS2022 (17.2.32516.85) found at:
gyp info find VS "path\to\Microsoft Visual Studio\2022\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn path\to\AppData\Local\Programs\Python\Python310\python.exe
gyp info spawn args [
gyp info spawn args   'path\\to\\steamworks-node-main\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'path\\to\\steamworks-node-main\\lib\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'path\\to\\steamworks-node-main\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'path\\to\\AppData\\Local\\node-gyp\\Cache\\17.4.7\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=path\\to\\AppData\\Local\\node-gyp\\Cache\\17.4.7',
gyp info spawn args   '-Dnode_gyp_dir=path\\to\\steamworks-node-main\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=path\\\\to\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\17.4.7\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=path\\to\\steamworks-node-main\\lib',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'path\\to\\steamworks-node-main\\lib\\build',        
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn path\to\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Выполняется последовательная сборка проектов в этом решении. Чтобы включить параллельную сборку, добавьте параметр "-m".
  steam_api_wrap.cxx
path\to\AppData\Local\node-gyp\Cache\17.4.7\include\node\v8-script.h(232,55): warning C4996: 'v8::Module::ResolveCallback': Use ResolveModuleCallback [path\to\steamworks-node-main\lib\build\steamworks.vcxproj]
path\to\steamworks-node-main\lib\steam_api_wrap.cxx(1248,22): warning C4311: 'argument' : conversion from "void *" to "long" [path\to\steamworks-node-main\lib\build\steamworks.vcxproj]
path\to\steamworks-node-main\lib\steam_api_wrap.cxx(1248,22): warning C4302: 'argument' : conversion from "void *" to "long" [path\to\steamworks-node-main\lib\build\steamworks.vcxproj]
  steamcallresult.cpp
  steamcallback.cpp
  win_delay_load_hook.cc
     Создается библиотека path\to\steamworks-node-main\lib\build\Release\steamworks.lib и объект path\to\steamworks-node-main\lib\build\Release\steamworks.exp
steam_api_wrap.obj : error LNK2019: reference to an unresolved external symbol "__declspec(dllimport) public: class std::shared_ptr<class v8::BackingStore> __cdecl v8::ArrayBuffer::GetBackingStore(void)" 
(__imp_?GetBackingStore@ArrayBuffer@v8@@QEAA?AV?$shared_ptr@VBackingStore@v8@@@std@@XZ) 
in function "void __cdecl _wrap_CallbackMsg_t_m_pubParam_set(class v8::Local<class v8::Name>,class v8::Local<class v8::Value>,class v8::PropertyCallbackInfo<void> const &)" 
(?_wrap_CallbackMsg_t_m_pubParam_set@@YAXV?$Local@VName@v8@@@v8@@V?$Local@VValue@v8@@@2@AEBV?$PropertyCallbackInfo@X@2@@Z). [path\to\steamworks-node-main\lib\build\steamworks.vcxproj]
path\to\steamworks-node-main\lib\build\Release\steamworks.node : fatal error LNK1120: unresolved externals: 1 [path\to\steamworks-node-main\lib\build\steamworks.vcxproj]
gyp ERR! build error 
gyp ERR! stack Error: `path\to\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (path\to\steamworks-node-main\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)      
gyp ERR! System Windows_NT 10.0.19044
gyp ERR! command "path\\to\\Node.js\\node.exe" "path\\to\\steamworks-node-main\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--directory=lib" "--target=17.4.7" "--arch=x64" "--dist-url=https://electronjs.org/headers"
gyp ERR! cwd path\to\steamworks-node-main\lib
gyp ERR! node -v v17.6.0
gyp ERR! node-gyp -v v8.4.1
gyp ERR! not ok
```

How to rebuild it with `electron-rebuild`? I tried but I didn't succeed

**Comment by Avocadocs** [comment]
[steamworks.node.zip](https://github.com/theace0296/steamworks-node/files/8852269/steamworks.node.zip)
So I tryed to recompile and I got this file, I did:
`node-gyp build` in myproject/node_modules/@theace0296/steamworks/lib and I move the file .node into myproject/node_modules/@theace0296/steamworks/bin but still not working i'm getting same error.
You said you was not using electron but maybe you use nw.js ?

**Comment by theace0296** [comment]
Pushed 1.0.2 that should help with electron support. Although I was seeing that Electron was getting errors because I used TypedArrays/ArrayBuffers, specifically: [GetBackingStore](https://v8docs.nodesource.com/node-16.15/d5/d6e/classv8_1_1_array_buffer.html#a017aa7d11e9e7cf5f5c3ce766a4e675d). I'm guessing this is a bug in Electron based off of this: electron/electron#29893

**Comment by repository** [comment]
were you able to getting it running with electron? i'm having a similar error with my setup 😧
```
App threw an error during load
Error: The module '\\?\********\release\app\node_modules\@theace0296\steamworks\build\Release\steamworks.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 103. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1812)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.Module._load (********\node_modules\runtime-required\runtime-required.js:34:23)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at ********\release\app\node_modules\@theace0296\steamworks\index.js:5:12
```
already using electron-rebuild
also using these configs as per https://github.com/cmake-js/cmake-js/issues/83#issuecomment-298512286
```
npm config set cmake_node_runtime="electron"
npm config set cmake_node_runtimeversion="18.2.3"
npm config set cmake_node_arch="x64"
```

**Comment by repository** [comment]
managed to get it to compile with the electron runtime.
had to add
```
"cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "20.0.2",
    "arch": "x64"
  }
```
to the package's `package.json`

and use an alternative method that doesn't involve `GetBackingStore()` in `steam_api.i`
example:
```
%typemap(in) int* {
	if ($input->IsInt32Array()) {
    v8::Local<v8::Int32Array> myarr = $input.As<v8::Int32Array>();
    v8::Local<v8::Object> local;
    node::Buffer::New(v8::Isolate::GetCurrent(), myarr->Buffer(), 0, myarr->ByteLength()).ToLocal(&local);
    $1 = (int*)((int*)node::Buffer::Data(local) + myarr->ByteOffset());
  } else {
    SWIG_exception_fail(SWIG_ArgError(SWIG_TypeError), "Illegal argument '$argnum' must be of type '""Int32Array""'");
  }
}
```

errors with generating types, but we should be fine without.
now i just have to figure out how to get it working with my specific setup, weird error while starting electron

**Comment by gaetandezeiraud** [comment]
@repository Can you share your modified `steam_api.i`?

**Comment by hubol** [comment]
@Brouilles I am guessing the culprit is line 188... I've tried some things but I basically don't know what I am doing, haha! I would also be curious what changes @repository made!
