### ISSUE TITLE
Unable to build on linux

### ISSUE THREAD

**Issue by dumbasPL** [theace0296/steamworks-node#3]
Building on Linux does not work.

The first problem seems to be with the swig. Mac and windows seem to have precompiled binaries but the Linux one does not. Building sig using `./configure && make` and adding
```json
"swig:linux": "export SWIG_LIB=$(node -p 'process.cwd()')/swig/swig-4.0.2/Lib && ./swig/swig-4.0.2/swig -Isteam -javascript -node -c++ -cpperraswarn ./lib/steam_api.i"
```
to the package.json fixes that(I think, not sure if that's correct)

The next problem seems to be with the backslashes in binding.gyp
```
make: *** No rule to make target 'Release/obj.target/steamworks/.\lib\steam_api_wrap.o', needed by 'Release/obj.target/steamworks.node'.  Stop.
```
Changing them to forward slashes fixes that but the build fails with thousands of errors
<details>
<summary>Preview</summary>

```
../lib/steam_api_wrap.cxx:5471:25: error: expected primary-expression before ‘>’ token
 5471 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5471:27: error: ‘jsresult’ was not declared in this scope
 5471 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5473:16: error: ‘SWIG_From_int’ was not declared in this scope
 5473 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultLimitedUserAccount));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultCantRemoveItem(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5490:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5490 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5490:25: error: expected primary-expression before ‘>’ token
 5490 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5490:27: error: ‘jsresult’ was not declared in this scope
 5490 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5492:16: error: ‘SWIG_From_int’ was not declared in this scope
 5492 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultCantRemoveItem));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultAccountDeleted(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5509:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5509 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5509:25: error: expected primary-expression before ‘>’ token
 5509 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5509:27: error: ‘jsresult’ was not declared in this scope
 5509 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5511:16: error: ‘SWIG_From_int’ was not declared in this scope
 5511 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultAccountDeleted));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultExistingUserCancelledLicense(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5528:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5528 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5528:25: error: expected primary-expression before ‘>’ token
 5528 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5528:27: error: ‘jsresult’ was not declared in this scope
 5528 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5530:16: error: ‘SWIG_From_int’ was not declared in this scope
 5530 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultExistingUserCancelledLicense));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultCommunityCooldown(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5547:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5547 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5547:25: error: expected primary-expression before ‘>’ token
 5547 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5547:27: error: ‘jsresult’ was not declared in this scope
 5547 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5549:16: error: ‘SWIG_From_int’ was not declared in this scope
 5549 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultCommunityCooldown));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultNoLauncherSpecified(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5566:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5566 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5566:25: error: expected primary-expression before ‘>’ token
 5566 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5566:27: error: ‘jsresult’ was not declared in this scope
 5566 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5568:16: error: ‘SWIG_From_int’ was not declared in this scope
 5568 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultNoLauncherSpecified));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultMustAgreeToSSA(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5585:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5585 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5585:25: error: expected primary-expression before ‘>’ token
 5585 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5585:27: error: ‘jsresult’ was not declared in this scope
 5585 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5587:16: error: ‘SWIG_From_int’ was not declared in this scope
 5587 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultMustAgreeToSSA));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultLauncherMigrated(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5604:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5604 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5604:25: error: expected primary-expression before ‘>’ token
 5604 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5604:27: error: ‘jsresult’ was not declared in this scope
 5604 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5606:16: error: ‘SWIG_From_int’ was not declared in this scope
 5606 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultLauncherMigrated));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultSteamRealmMismatch(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5623:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5623 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5623:25: error: expected primary-expression before ‘>’ token
 5623 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5623:27: error: ‘jsresult’ was not declared in this scope
 5623 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5625:16: error: ‘SWIG_From_int’ was not declared in this scope
 5625 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultSteamRealmMismatch));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultInvalidSignature(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5642:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5642 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5642:25: error: expected primary-expression before ‘>’ token
 5642 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5642:27: error: ‘jsresult’ was not declared in this scope
 5642 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5644:16: error: ‘SWIG_From_int’ was not declared in this scope
 5644 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultInvalidSignature));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultParseFailure(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5661:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5661 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5661:25: error: expected primary-expression before ‘>’ token
 5661 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5661:27: error: ‘jsresult’ was not declared in this scope
 5661 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5663:16: error: ‘SWIG_From_int’ was not declared in this scope
 5663 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultParseFailure));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultNoVerifiedPhone(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5680:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5680 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5680:25: error: expected primary-expression before ‘>’ token
 5680 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5680:27: error: ‘jsresult’ was not declared in this scope
 5680 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5682:16: error: ‘SWIG_From_int’ was not declared in this scope
 5682 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultNoVerifiedPhone));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultInsufficientBattery(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5699:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5699 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5699:25: error: expected primary-expression before ‘>’ token
 5699 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5699:27: error: ‘jsresult’ was not declared in this scope
 5699 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5701:16: error: ‘SWIG_From_int’ was not declared in this scope
 5701 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultInsufficientBattery));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultChargerRequired(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5718:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5718 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5718:25: error: expected primary-expression before ‘>’ token
 5718 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5718:27: error: ‘jsresult’ was not declared in this scope
 5718 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5720:16: error: ‘SWIG_From_int’ was not declared in this scope
 5720 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultChargerRequired));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EResultCachedCredentialInvalid(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5737:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5737 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5737:25: error: expected primary-expression before ‘>’ token
 5737 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5737:27: error: ‘jsresult’ was not declared in this scope
 5737 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5739:16: error: ‘SWIG_From_int’ was not declared in this scope
 5739 |     jsresult = SWIG_From_int(static_cast< int >(k_EResultCachedCredentialInvalid));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_K_EResultPhoneNumberIsVOIP(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5756:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5756 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5756:25: error: expected primary-expression before ‘>’ token
 5756 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5756:27: error: ‘jsresult’ was not declared in this scope
 5756 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5758:16: error: ‘SWIG_From_int’ was not declared in this scope
 5758 |     jsresult = SWIG_From_int(static_cast< int >(K_EResultPhoneNumberIsVOIP));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EVoiceResultOK(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5775:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5775 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5775:25: error: expected primary-expression before ‘>’ token
 5775 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5775:27: error: ‘jsresult’ was not declared in this scope
 5775 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5777:16: error: ‘SWIG_From_int’ was not declared in this scope
 5777 |     jsresult = SWIG_From_int(static_cast< int >(k_EVoiceResultOK));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EVoiceResultNotInitialized(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5794:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5794 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5794:25: error: expected primary-expression before ‘>’ token
 5794 |     v8::Handle<v8::Value> jsresult;
      |                         ^
../lib/steam_api_wrap.cxx:5794:27: error: ‘jsresult’ was not declared in this scope
 5794 |     v8::Handle<v8::Value> jsresult;
      |                           ^~~~~~~~
../lib/steam_api_wrap.cxx:5796:16: error: ‘SWIG_From_int’ was not declared in this scope
 5796 |     jsresult = SWIG_From_int(static_cast< int >(k_EVoiceResultNotInitialized));
      |                ^~~~~~~~~~~~~
../lib/steam_api_wrap.cxx: In function ‘SwigV8ReturnValue _wrap_k_EVoiceResultNotRecording(v8::Local<v8::Name>, const SwigV8PropertyCallbackInfo&)’:
../lib/steam_api_wrap.cxx:5813:9: error: ‘Handle’ is not a member of ‘v8’; did you mean ‘JobHandle’?
 5813 |     v8::Handle<v8::Value> jsresult;
      |         ^~~~~~
      |         JobHandle
../lib/steam_api_wrap.cxx:5813:25: error: expected primary-expression before ‘>’ token
 5813 |     v8::Handle<v8::Value> jsresult;
      |                         ^
```
</details>

**Comment by theace0296** [comment]
Just released v1.1.0, the Linux SWIG binary is now part of the package also. I don't have a fully-dedicated Linux development set up, but it does compile and attempt to connect to Steam. 

Let me know if you continue having any issues!

**Comment by dumbasPL** [comment]
Here is an easy to reproduce example of the new version failing using the `node:16` docker image

```
docker run -v /home/nezu/Downloads/sdk:/sdk --rm -it node:16 bash                                                                                              3s
root@58b96b4a1881:/# 
root@58b96b4a1881:/# 
root@58b96b4a1881:/# mkdir app
root@58b96b4a1881:/# cd app
root@58b96b4a1881:/app# npm init -y
Wrote to /app/package.json:

{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


root@58b96b4a1881:/app# npm install @theace0296/steamworks

added 234 packages, and audited 235 packages in 8s

41 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice 
npm notice New minor version of npm available! 8.11.0 -> 8.16.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.16.0
npm notice Run npm install -g npm@8.16.0 to update!
npm notice 
root@58b96b4a1881:/app# ls /sdk/
Readme.txt  glmgr  public  redistributable_bin	steamworksexample  tools
root@58b96b4a1881:/app# STEAMWORKS_SDK_PATH=/sdk npx steamworks-init

> @theace0296/steamworks@1.1.0 preinstall-steam
> node ./utilities/preinstall-steam.js


> @theace0296/steamworks@1.1.0 swig
> run-script-os


> @theace0296/steamworks@1.1.0 swig:default
> export SWIG_LIB=$(node -p 'process.cwd()')/swig/lib && ./swig/swig -Isteam -javascript -node -c++ -cpperraswarn -ignoremissing -includeall ./lib/steam_api.i

:1: Warning 201: Unable to find 'swig.swg'
:3: Warning 201: Unable to find 'javascript.swg'
./lib/steam_api.i:1: Warning 201: Unable to find 'windows.i'
./lib/steam_api.i:2: Warning 201: Unable to find 'typemaps.i'
steam/steam_api_internal.h:14: Warning 201: Unable to find 'string.h'
steam/matchmakingtypes.h:21: Warning 201: Unable to find 'stdio.h'
steam/matchmakingtypes.h:22: Warning 201: Unable to find 'string.h'
steam/steamnetworkingtypes.h:11: Warning 201: Unable to find 'string.h'
steam/steamnetworkingtypes.h:12: Warning 201: Unable to find 'stdint.h'
./lib/steamcallresult.h:2: Warning 201: Unable to find 'stdio.h'
./lib/steamcallback.h:2: Warning 201: Unable to find 'stdio.h'
./lib/steam_api.i:91: Error: Syntax error in input(1).
node:child_process:902
    throw err;
    ^

Error: Command failed: npm run swig
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (/app/node_modules/@theace0296/steamworks/utilities/init.js:14:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 74,
  stdout: null,
  stderr: null
}
root@58b96b4a1881:/app#
```

**Comment by theace0296** [comment]
Go ahead and try v1.1.1, had a typo in the swig:default script pointing to swig/lib instead of swig/Lib. Also, you will need to install cmake now (part of v1.1.0) if you haven't already.

**Comment by dumbasPL** [comment]
It does build now but fails at `generate-types`
```
Copying Steam binary files...
[100%] Built target steamworks

> @theace0296/steamworks@1.1.1 generate-types
> node ./utilities/generate_typings.js

[S_API] SteamAPI_Init(): SteamAPI_IsSteamRunning() did not locate a running instance of Steam.
dlopen failed trying to load:
/root/.steam/sdk64/steamclient.so
with error:
/root/.steam/sdk64/steamclient.so: cannot open shared object file: No such file or directory
[S_API] SteamAPI_Init(): Sys_LoadModule failed to load: /root/.steam/sdk64/steamclient.so
Error: Steam API failed to initialize!
    at SteamWorks.Init (/app/node_modules/@theace0296/steamworks/index.js:225:13)
    at new SteamWorks (/app/node_modules/@theace0296/steamworks/index.js:77:12)
    at Object.<anonymous> (/app/node_modules/@theace0296/steamworks/utilities/generate_typings.js:17:20)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
/app/node_modules/@theace0296/steamworks/utilities/generate_typings.js:204
if (SteamWorks.SteamAPI.IsSteamRunning()) {
                        ^

TypeError: SteamWorks.SteamAPI.IsSteamRunning is not a function
    at Object.<anonymous> (/app/node_modules/@theace0296/steamworks/utilities/generate_typings.js:204:25)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47
node:child_process:902
    throw err;
    ^

Error: Command failed: npm run generate-types
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at Object.<anonymous> (/app/node_modules/@theace0296/steamworks/utilities/init.js:16:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 694,
  stdout: null,
  stderr: null
}
```

Is steam required to be installed and running for this? Why would that be?

**Comment by theace0296** [comment]
Yes, Steam has to be installed and running. This is using the Steam SDK, which is primarily for game developers to interact with the steam client.

**Comment by dumbasPL** [comment]
Well, to be fair my use case is the least standard one and I already moved to a rust implementation. I just needed to interact with the steam master servers for "reasons".
